### ISSUE TITLE
Debian 10 - play crashes on step "Ensure ufw is disabled"

### ISSUE THREAD

**Issue by DeamonMV** [skandyla/ansible-role-iptables#3]
Hello

I have faced problem on Debian 10. 

Playbook crashed on step: `TASK [iptables : Ensure ufw is disabled]` with message

```
msg: 'Failed to find required executable ufw in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
```

I think it's will be good to check before if `ufw` is really installed, so I came up with this solution:

```
- name: Check if ufw is installed
  package_facts:
    manager: "auto"

- name: Ensure ufw is disabled
  ufw: state=disabled
  when: "'ufw' in ansible_facts.packages"
```

Can you please check it, and if it's a good one, add it to repository.

Thank you.
